##
##  Makefile -- Build procedure for sample t2t Apache module
##  Autogenerated via ``apxs -n t2t -g''.
##

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional user defines, includes and libraries
#DEF=-Dmy_define=my_value
INC=-I/usr/include/python2.4
LIB=-lpython2.4

#   the default target
all: mod_t2t.so

#   compile the DSO file
mod_t2t.so: mod_t2t.c
	$(APXS) -c $(DEF) $(INC) $(LIB) mod_t2t.c

#   install the DSO file into the Apache installation
#   and activate it in the Apache configuration
install: all
	$(APXS) -i -a -n 't2t' mod_t2t.so

#   cleanup
clean:
	-rm -f mod_t2t.o mod_t2t.so

#   simple test
test: reload
	lynx -mime_header http://localhost/t2t

#   reload the module by installing and restarting Apache
reload: install restart

#   the general Apache start/restart/stop procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

